#!/bin/bash
source ./venv/bin/activate 2>/dev/null
if [ "$?" -eq "1" ]
then
    echo "Error on activating venv. Have you created it? (python3 -m venv venv)"
    exit 1
fi
mkdir tmp
cp -r VKInfoSite tmp/VKInfoSite
rm -r VKInfoSite
echo "===========================================Start loading requirements==========================================="
pip install --no-cache-dir -r requirements.txt
echo "=========================================Successfully loaded requeirments======================================="
django-admin startproject VKInfoSite
cd VKInfoSite
python manage.py startapp main
python manage.py startapp vksearch
cd ..
rm -r VKInfoSite
cp -r tmp/VKInfoSite VKInfoSite
rm -r tmp
echo "===========================================Initialized django app==============================================="
echo "===========================================Enter configuration data:============================================"
read -p "Vk token: " TOKEN

read -p "Mongo host: " MDB_HOST
if [ "${MDB_HOST}" == "" ]
then
    MDB_HOST="localhost"
fi

read -p "Mongo port: " MDB_PORT
if [ "${MDB_PORT}" == "" ]
then
    MDB_PORT="27017"
fi

read -p "Neo4j URL: " NEO4J_URL
if [ "${NEO4J_URL}" == "" ]
then
    NEO4J_URL="bolt://localhost:7687"
fi

read -p "Neo4j user: " NEO4J_USER
if [ "${NEO4J_USER}" == "" ]
then
    NEO4J_USER="neo4j"
fi

read -p "Neo4j pass: " NEO4J_PASS

if [ "${NEO4J_PASS}" == "" ]
then
    NEO4J_PASS="pass"
fi

rm ./VKInfoSite/config/config.json 2>/dev/null
CONFIG="{\"mdb_host\": \"${MDB_HOST}\", \"mdb_port\": ${MDB_PORT}, \"neo_url\": \"${NEO4J_URL}\", \"neo_user\": \"${NEO4J_USER}\", \"neo_pass\": \"${NEO4J_PASS}\", \"vk_token\": \"${TOKEN}\"}"
echo "${CONFIG}" >> ./VKInfoSite/config/config.json 2>/dev/null
echo "===================================Initialized configuration file config.json===================================="
