#!/bin/bash

echo "=======================================Start preparing Docker environment======================================="
sudo /bin/bash ./project_update .
echo "====================================Start building VKUserInfo Docker conteiner=================================="
sudo docker build -t vkuserinfo docker
echo "=======================Project was successfully build. Enter 'docker-compose up' to run it======================"