#!/bin/bash

if [ $# -lt 1 ]
then
    echo "Error: required params: PROJECT_DIR"
    exit 1
fi

if [ "$1" == "default" ]
then
    PROJECT_DIR="/home/leadness/PycharmProjects/VKUserInfo"
    echo "Project directory: ${PROJECT_DIR}"
else
    if [ -d "$1" ]
    then
        PROJECT_DIR="$1"
        if [ "$1" == "." ]
        then
            echo "Project directory: $(pwd)"
        else
            echo "Project directory: ${PROJECT_DIR}"
        fi
    else
        echo "Error: ${1} is not dir"
        exit 1
    fi
fi

rm "./docker/requirments.txt" 2> /dev/null
rm -r "./docker/VKInfoSite" 2> /dev/null
cp "${PROJECT_DIR}/requirements.txt" "./docker/requirements.txt"
cp -r "${PROJECT_DIR}/VKInfoSite" "./docker/VKInfoSite"
rm -r "./docker/VKInfoSite/__pycache__"

CONFIG=$(cat ./docker/VKInfoSite/config/config.json)
rm "./docker/VKInfoSite/config/config.json"
rm "./docker/VKInfoSite/config/default_config.json" 
CONFIG="${CONFIG/bolt:\/\/localhost:7687/graphdb}"
CONFIG="${CONFIG/27017/\"\"}"
CONFIG="${CONFIG/\"localhost\"/\"mongodb\"}"
echo "${CONFIG}" >> "./docker/VKInfoSite/config/config.json"
echo "${CONFIG}" >> "./docker/VKInfoSite/config/default_config.json"

CONFIG=$(cat ./docker/VKInfoSite/config.py)
rm "./docker/VKInfoSite/config.py"
echo "${CONFIG//\'config/\'/app/VKInfoSite/config}" >> "./docker/VKInfoSite/config.py"
