#!/bin/bash

if [ $# -lt 1 ]
then
    echo "Error: required params: PROJECT_DIR"
    exit 1
fi

if [ "$1" == "default" ]
then
    PROJECT_DIR="/home/leadness/PycharmProjects/VKUserInfo"
else
    if [ -d "$1" ]
    then
        PROJECT_DIR="$1"
    else
        echo "Error: ${1} is not dir"
        exit 1
    fi
fi

echo "Project directory: ${PROJECT_DIR}"

rm "./docker/requirments.txt" 2> /dev/null
rm -r "./docker/VKInfoSite" 2> /dev/null
cp "${PROJECT_DIR}/requirements.txt" "./docker/requirements.txt"
cp -r "${PROJECT_DIR}/VKInfoSite" "./docker/VKInfoSite"
rm -r "./docker/VKInfoSite/__pycache__"

CONFIG=$(cat ./docker/VKInfoSite/config/config.json)
rm "./docker/VKInfoSite/config/config.json"
rm "./docker/VKInfoSite/config/default_config.json" 
CONFIG="${CONFIG/bolt:\/\/localhost:7687/graphdb}"
CONFIG="${CONFIG/27017/\"\"}"
CONFIG="${CONFIG/\"localhost\"/\"mongodb\"}"
echo "${CONFIG}" >> "./docker/VKInfoSite/config/config.json"
echo "${CONFIG}" >> "./docker/VKInfoSite/config/default_config.json"

VIEWS=$(cat ./docker/VKInfoSite/dashboard/dash_app.py)
rm "./docker/VKInfoSite/MongoDB.py"
echo "${VIEWS//(\'config/(\'/app/VKInfoSite/config}" >> "./docker/VKInfoSite/MongoDB.py"

VIEWS=$(cat ./docker/VKInfoSite/main/views.py)
rm "./docker/VKInfoSite/main/views.py"
echo "${VIEWS//(\'config/(\'/app/VKInfoSite/config}" >> "./docker/VKInfoSite/main/views.py"

VIEWS=$(cat ./docker/VKInfoSite/main/views.py)
rm "./docker/VKInfoSite/vksearch/views.py"
echo "${VIEWS//(\'config/(\'/app/VKInfoSite/config}" >> "./docker/VKInfoSite/mavksearchin/views.py"

VIEWS=$(cat ./docker/VKInfoSite/dashboard/dash_app.py)
rm "./docker/VKInfoSite/dashboard/dash_app.py"
echo "${VIEWS//(\'config/(\'/app/VKInfoSite/config}" >> "./docker/VKInfoSite/dashboard/dash_app.py"

VIEWS=$(cat ./docker/VKInfoSite/dashboard/DashGraphs.py)
rm "./docker/VKInfoSite/dashboard/DashGraphs.py"
echo "${VIEWS//(\'config/(\'/app/VKInfoSite/config}" >> "./docker/VKInfoSite/dashboard/DashGraphs.py"
