#!/bin/bash

python3 -m venv venv
echo "Created virtual environment..."
. ./venv/bin/activate
mkdir tmp
cp -r VKInfoSite tmp/VKInfoSite
rm -r VKInfoSite

echo "===========================================Start loading requirements==========================================="
pip install --no-cache-dir -r requirements.txt
echo "=========================================Successfully loaded requirments======================================="
django-admin startproject VKInfoSite
GENERATED_SECRET_KEY=$(cat ./VKInfoSite/VKInfoSite/settings.py | grep SECRET_KEY | cut -d "'" -f 2)

rm -r VKInfoSite
cp -r tmp/VKInfoSite VKInfoSite
rm -r tmp

SETTINGS="$(echo "$(cat ./deploy/settings)")"
SETTINGS="${SETTINGS/GENERATED_SECRET_KEY/${GENERATED_SECRET_KEY}}"

echo "===========================================Initialized django app==============================================="
echo "==========================================Enter configuration data============================================="
read -r -p "MongoDB host (default: localhost) " MONGO_HOST
if [ "${MONGO_HOST}" == "" ]
then
  MONGO_HOST="localhost"
fi
SETTINGS="${SETTINGS/MONGO_HOST/${MONGO_HOST}}"

read -r -p "MongoDB port (default: 27017): " MONGO_PORT
if [ "${MONGO_PORT}" == "" ]
then
  MONGO_PORT="27017"
fi
SETTINGS="${SETTINGS/MONGO_PORT/${MONGO_PORT}}"

read -r -p "MongoDB database name (default: 'vktracker'): " MONGO_DBNAME
if [ "${MONGO_DBNAME}" == "" ]
then
  MONGO_DBNAME="vktracker"
fi
SETTINGS="${SETTINGS/MONGO_DBNAME/${MONGO_DBNAME}}"
SETTINGS="${SETTINGS/MONGO_TESTDBNAME/test_${MONGO_DBNAME}}"

read -r -p "Neo4j URL (default: 'http://localhost:7474'): " NEO4J_URL
if [ "${NEO4J_URL}" == "" ]
then
  NEO4J_URL="http://localhost:7474"
fi
SETTINGS="${SETTINGS/NEO4J_URL/${NEO4J_URL}}"

read -r -p "Neo4j user (default: 'neo4j'): " NEO4J_USER
if [ "${NEO4J_USER}" == "" ]
then
  NEO4J_USER="neo4j"
fi
SETTINGS="${SETTINGS/NEO4J_USER/${NEO4J_USER}}"

read -r -p "Neo4j password (default: 'neo4j'): " NEO4J_PASSWORD
if [ "${NEO4J_PASSWORD}" == "" ]
then
  NEO4J_PASSWORD="neo4j"
fi
SETTINGS="${SETTINGS/NEO4J_PASSWORD/${NEO4J_PASSWORD}}"

echo "${SETTINGS}" > ./VKInfoSite/VKInfoSite/settings.py

echo "==========================================Initialized configuration============================================="
echo "===========================================Enter superuser info==============================================="
python VKInfoSite/manage.py createsuperuser
