#!/bin/bash

SETTINGS="$(echo "$(cat ./deploy/settings)")"

read -r -p "Project secret key: " GENERATED_SECRET_KEY
if [ "${GENERATED_SECRET_KEY}" == "" ]
then
  echo "Error: secret key must be specify"
  exit 1
fi

SETTINGS="${SETTINGS/GENERATED_SECRET_KEY/${GENERATED_SECRET_KEY}}"
SETTINGS="${SETTINGS/MONGO_HOST/mongo}"
SETTINGS="${SETTINGS/MONGO_PORT/27017}"
SETTINGS="${SETTINGS/MONGO_DBNAME/vktracker}"
SETTINGS="${SETTINGS/MONGO_TESTDBNAME/test_vktracker}"
SETTINGS="${SETTINGS/NEO4J_URL/http://neo4j:7474}"
SETTINGS="${SETTINGS/NEO4J_USER/neo4j}"
SETTINGS="${SETTINGS/NEO4J_PASSWORD/neo4j}"

echo "${SETTINGS}" > ./deploy/container_settings

read -r -p "Add vk-tracker as unit in systemd? [y/n]" ANSWER
if [ "${ANSWER}" == "y" ]
then
  echo "Settings for docker-compose are configured. Run app by entering: docker-compose up"
  exit 0
fi

read -r -p "Enter docker-compose working directory (default: $(pwd): " WORKDIR
if [ "${WORKDIR}" == "" ]
then
  WORKDIR="$(pwd)"
fi

SERVICE="$(echo "$(cat ./deploy/vk-tracker.service)")"
SERVICE="${SERVICE/VK_TRACKER_WORKDIR/${WORKDIR}}"
echo "${SERVICE}" > ./deploy/vk-tracker.service

sudo cp ./deploy/vk-tracker.service /etc/systemd/system/vk-tracker.service
sudo systemctl daemon-reload
sudo systemctl start vk-tracker
