#!/bin/bash

python3 /app/VKInfoSite/manage.py makemigrations
python3 /app/VKInfoSite/manage.py migrate
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', '', 'admin')" | python3 /app/VKInfoSite/manage.py shell

python3 /app/VKInfoSite/manage.py runserver 0.0.0.0:80 --noreload

